/**
 * Error Constants
 * 
 * Constants related to error handling, such as error codes,
 * messages, and other error-related properties.
 */

// Error Codes
export const ERROR_CODES = {
  // Authentication Errors
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',

  // Resource Errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_UNAVAILABLE: 'RESOURCE_UNAVAILABLE',

  // Permission Errors
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

// Error Messages
export const ERROR_MESSAGES = {
  [ERROR_CODES.AUTHENTICATION_FAILED]: 'Authentication failed. Please try again.',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password.',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Your session has expired. Please log in again.',
  [ERROR_CODES.TOKEN_INVALID]: 'Invalid session token.',
  [ERROR_CODES.SESSION_EXPIRED]: 'Your session has expired. Please log in again.',
  [ERROR_CODES.VALIDATION_ERROR]: 'Please check your input and try again.',
  [ERROR_CODES.INVALID_INPUT]: 'The provided input is invalid.',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Please fill in all required fields.',
  [ERROR_CODES.INVALID_FORMAT]: 'The provided format is invalid.',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'The requested resource was not found.',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'The resource already exists.',
  [ERROR_CODES.RESOURCE_CONFLICT]: 'There was a conflict with the resource.',
  [ERROR_CODES.RESOURCE_UNAVAILABLE]: 'The resource is currently unavailable.',
  [ERROR_CODES.PERMISSION_DENIED]: 'You do not have permission to perform this action.',
  [ERROR_CODES.UNAUTHORIZED_ACCESS]: 'Unauthorized access attempt.',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 'You do not have sufficient permissions.',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'An internal server error occurred.',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'The service is currently unavailable.',
  [ERROR_CODES.DATABASE_ERROR]: 'A database error occurred.',
  [ERROR_CODES.NETWORK_ERROR]: 'A network error occurred. Please check your connection.',
} as const;

// Error Status Codes
export const ERROR_STATUS_CODES = {
  [ERROR_CODES.AUTHENTICATION_FAILED]: 401,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.TOKEN_INVALID]: 401,
  [ERROR_CODES.SESSION_EXPIRED]: 401,
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_FORMAT]: 400,
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 409,
  [ERROR_CODES.RESOURCE_CONFLICT]: 409,
  [ERROR_CODES.RESOURCE_UNAVAILABLE]: 503,
  [ERROR_CODES.PERMISSION_DENIED]: 403,
  [ERROR_CODES.UNAUTHORIZED_ACCESS]: 403,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.NETWORK_ERROR]: 503,
} as const; 